src/main/java/co/edu/ucc/coe/model/Peticion.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.ucc.coe.model;

import co.edu.ucc.coe.base.CamposComunesdeEntidad;
import java.io.Serializable;
import javax.persistence.Entity;


/**
 *
 * @author wilme
 */
@Entity
public class Peticion extends CamposComunesdeEntidad implements Serializable {

    String NombreUsuario;
    String IDdispositivoRealizador;

    public String getNombreUsuario() {
        return NombreUsuario;
    }

    public void setNombreUsuario(String NombreUsuario) {
        this.NombreUsuario = NombreUsuario;
    }

    public String getIDdispositivoRealizador() {
        return IDdispositivoRealizador;
    }

    public void setIDdispositivoRealizador(String IDdispositivoRealizador) {
        this.IDdispositivoRealizador = IDdispositivoRealizador;
    }
    
    
}

src/main/webapp/css/templates/base.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <ui:composition>
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <!--<div class="navbar nav_title" style="border: 0;">
                    <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>COE</span></a>
                </div>-->
                <div class="clearfix"></div>
                <!-- menu profile quick info -->
                <!--<ui:include src="menu_profile.xhtml"/>-->
                <!-- /menu profile quick info -->
                <br />
                <!-- sidebar menu -->
                <ui:include src="sidebar_menu.xhtml"/>
                <!-- /sidebar menu -->
            </div>
        </div>
        <!-- top navigation -->
        <ui:include src="top_navigation.xhtml"/>
        <!-- /top navigation -->

    </ui:composition>
</html>

src/main/webapp/css/templates/base_admin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <ui:composition>
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <!--<div class="navbar nav_title" style="border: 0;">
                    <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>COE</span></a>
                </div>-->
                <div class="clearfix"></div>
                <!-- menu profile quick info -->
                <!--<ui:include src="menu_profile.xhtml"/>-->
                <!-- /menu profile quick info -->
                <br />
                <!-- sidebar menu -->
                <ui:include src="sidebar_menu_admin.xhtml"/>
                <!-- /sidebar menu -->
            </div>
        </div>
        <!-- top navigation -->
        <ui:include src="top_navigation.xhtml"/>
        <!-- /top navigation -->

    </ui:composition>
</html>

src/main/webapp/css/templates/footer_scripts.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:composition>
        <!-- jQuery -->
        <!--<script src="/coe/css/vendors/jquery/dist/jquery.min.js"></script>-->
        <!-- Bootstrap -->
        <script src="/coe/css/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="/coe/css/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="/coe/css/vendors/nprogress/nprogress.js"></script>
        <!-- Chart.js -->
        <script src="/coe/css/vendors/Chart.js/dist/Chart.min.js"></script>
        <!-- gauge.js -->
        <script src="/coe/css/vendors/gauge.js/dist/gauge.min.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="/coe/css/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="/coe/css/vendors/iCheck/icheck.min.js"></script>
        <!-- Skycons -->
        <script src="/coe/css/vendors/skycons/skycons.js"></script>
        <!-- Flot -->
        <!--<script src="/coe/css/vendors/Flot/jquery.flot.js"></script>
        <script src="/coe/css/vendors/Flot/jquery.flot.pie.js"></script>
        <script src="/coe/css/vendors/Flot/jquery.flot.time.js"></script>
        <script src="/coe/css/vendors/Flot/jquery.flot.stack.js"></script>
        <script src="/coe/css/vendors/Flot/jquery.flot.resize.js"></script>-->
        <!-- Flot plugins -->
        <!--<script src="/coe/css/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
        <script src="/coe/css/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
        <script src="/coe/css/vendors/flot.curvedlines/curvedLines.js"></script>-->
        <!-- DateJS -->
        <script src="/coe/css/vendors/DateJS/build/date.js"></script>
        <!-- JQVMap -->
        <script src="/coe/css/vendors/jqvmap/dist/jquery.vmap.js"></script>
        <script src="/coe/css/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
        <script src="/coe/css/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="/coe/css/production/js/moment/moment.min.js"></script>
        <script src="/coe/css/production/js/datepicker/daterangepicker.js"></script>

        <!-- Custom Theme Scripts -->
        <script src="/coe/css/build/js/custom.min.js"></script>

    </ui:composition>
</html>

src/main/webapp/css/templates/growl.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:composition>
        <h:panelGroup id="growl-total">
            <p:growl id="growl-info" showDetail="true"  rendered="#{facesContext.maximumSeverity.ordinal eq 0}"/> 
            <p:growl id="growl-warn" showDetail="true"  rendered="#{facesContext.maximumSeverity.ordinal eq 1}"/> 
            <p:growl id="growl-error" showDetail="true"  rendered="#{facesContext.maximumSeverity.ordinal eq 2}"/> 
            <p:growl id="growl-fatal" showDetail="true" rendered="#{facesContext.maximumSeverity.ordinal eq 3}"/> 
        </h:panelGroup>
        <!--
            0 -> info
            1 -> warn
            2 -> error
            3 -> fatal
        -->
    </ui:composition>
</html>

src/main/webapp/css/templates/head_config.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:composition>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>

        <!-- Bootstrap -->
        <link href="/coe/css/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet"/>
        <!-- Font Awesome -->
        <link href="/coe/css/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
        <!-- NProgress -->
        <link href="/coe/css/vendors/nprogress/nprogress.css" rel="stylesheet"/>
        <!-- iCheck -->
        <link href="/coe/css/vendors/iCheck/skins/flat/green.css" rel="stylesheet"/>
        <!-- bootstrap-progressbar -->
        <link href="/coe/css/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet"/>
        <!-- JQVMap -->
        <link href="/coe/css/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet"/>

        <!-- Custom Theme Style -->
        <link href="/coe/css/build/css/custom.min.css" rel="stylesheet"/>
        
        <!--<ui:include src="/css/templates/growl.xhtml"/>-->
    </ui:composition>
</html>

src/main/webapp/css/templates/menu_profile.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <ui:composition>
        <!-- menu profile quick info -->
                        <div class="profile">
                            <div class="profile_pic">
                                <img src="/coe/css/production/images/img.jpg" alt="..." class="img-circle profile_img"/>
                            </div>
                            <div class="profile_info">
                                <span></span>
                                <h2>John Doe</h2>
                            </div>
                        </div>
        
    </ui:composition>
</html>

src/main/webapp/css/templates/sidebar_menu.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">
    <ui:composition>
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print menu_fixed">
            <!--main_menu -->
            <div class="menu_section">
                <h3>Menu</h3>
                <ul class="nav side-menu">
                    <li><a href="/coe/usuario/index.xhtml"><i class="fa fa-home"></i> Inicio</a></li>

                    <c:forEach var="row"  items="#{MbMenu.listaVistas}">
                        <li><a href="/coe/usuario/#{row.ruta}"><i class="#{row.icono}"></i> #{row.nombre}<span class="fa"></span> </a></li>
                    </c:forEach>
                </ul>
            </div>


        </div>
        <!-- /sidebar menu -->
    </ui:composition>
</html>

src/main/webapp/css/templates/sidebar_menu_admin.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <ui:composition>
        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>Menu</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-lock"></i> Seguridad <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="gestionrol.xhtml">Roles</a></li>
                            <li><a href="vistas.xhtml">Vistas Rol</a></li>
                            <li><a href="gestionpermisos.xhtml">Permisos</a></li>
                        </ul>
                    </li>

                    <!--<li><a href="gestionnotificacion.xhtml"><i class="fa fa-envelope"></i>Notificaciones</a></li>-->
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <!--<div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>-->
        <!-- /menu footer buttons -->        

    </ui:composition>
</html>

src/main/webapp/css/templates/top_navigation.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition>
        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                <img src="http://#{MbDatosBasicos.ip}:8080/coe/imagenperfilservlet?id=#{mbLoguin.usuario.id}" alt=""/><p:outputLabel value="#{mbLoguin.usuario.nombreUsuario}" />
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="/coe/usuario/perfil.xhtml"> Modificar datos personales</a></li>
                                <li>
                                    <h:form>
                                        <h:commandLink styleClass="fa" action="#{mbLoguin.accionLogout()}" value="Cerrar Sesion" >
                                            <i class="fa fa-sign-out pull-right"></i>
                                        </h:commandLink>
                                    </h:form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->


    </ui:composition>
</html>